"""YAML serializer for workspace entities.

Uses ruamel.yaml in round-trip mode so that:
  * Comments survive read → modify → write
  * Key order is preserved (Pydantic already emits id/layer/version first)
  * Multi-line strings keep their style (block vs flow)
  * Inline aliases / anchors are honored

Paired with :func:`load_yaml_text` so callers don't have to know about ruamel.
"""

from io import StringIO
from typing import Any

from ruamel.yaml import YAML


def _build_yaml() -> YAML:
    """Return a configured ruamel YAML round-trip instance.

    Settings chosen to match the legacy PyYAML output as closely as possible,
    so diffs across the migration stay reviewable.
    """
    y = YAML(typ="rt")  # round-trip — preserves comments + ordering
    y.indent(mapping=2, sequence=4, offset=2)
    y.allow_unicode = True
    y.default_flow_style = False
    y.preserve_quotes = True
    y.width = 4096  # do not wrap long lines (descriptions stay on one line)
    return y


class AskYamlSerializer:
    """Round-trip-aware YAML writer for the workspace.

    Accepts plain dicts (new construction) or ``CommentedMap`` instances
    loaded by :func:`load_yaml_text` — both produce clean YAML. Round-tripping
    a ``CommentedMap`` preserves the original file's comments.
    """

    HEADER = "# Auto-generated by Onibex ASK Platform\n---\n"

    def __init__(self) -> None:
        self._yaml = _build_yaml()

    def to_yaml(self, data: Any) -> str:
        try:
            buf = StringIO()
            self._yaml.dump(data, buf)
            return self.HEADER + buf.getvalue()
        except Exception as e:
            raise ValueError(f"Error al serializar el diccionario a YAML: {e!s}") from e


def load_yaml_text(content: str) -> Any:
    """Parse a YAML string in round-trip mode (preserves comments + order).

    Returns ``None`` for empty / non-mapping documents (matches the legacy
    ``yaml.safe_load`` behavior callers already handle). The returned object
    is dict-like (``CommentedMap``) so ``isinstance(x, dict)`` checks pass.
    """
    if not content or not content.strip():
        return None
    yaml = _build_yaml()
    return yaml.load(content)


def dump_yaml(data: Any) -> str:
    """Serialize a dict / ``CommentedMap`` to YAML text — no auto-generated header.

    Drop-in replacement for the old ``yaml.dump(data, sort_keys=False,
    allow_unicode=True)``: key order is preserved (ruamel never sorts) and
    unicode is emitted literally. Use this instead of PyYAML so the whole
    codebase shares one YAML 1.2 parser/emitter.
    """
    buf = StringIO()
    _build_yaml().dump(data, buf)
    return buf.getvalue()
