# SPDX-License-Identifier: LicenseRef-PolyForm-Strict-1.0.0 OR LicenseRef-PolyForm-Free-Trial-1.0.0
# Copyright (c) 2026 Onibex, LLC. All rights reserved.
#
# Part of Onibex ASK — Agentic Semantic Knowledge.
# Source-available under PolyForm Strict 1.0.0 / PolyForm Free Trial 1.0.0.
# Commercial licenses: contact@onibex.com — see LICENSE.

apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: ask-orchestrator-permissive
  namespace: workforce
spec:
  selector:
    matchLabels:
      app: ask-orchestrator
  mtls:
    mode: PERMISSIVE
